<?php
$_info = $this->getInfo();
?>
<dl class="payment-method ebanx_boleto">
    <dt class="title">Test</dt>
<!--    <dt class="title">--><?php //echo $block->escapeHtml($block->getMethod()->getTitle()) ?><!--</dt>-->
<!--    <dt class="title">--><?php //echo $_info->getAdditionalInformation('social_security_number'); ?><!--</dt>-->
<!--    <dt class="title">--><?php //echo $_info->getAdditionalInformation('firstname'); ?><!--</dt>-->
<!--    <dt class="title">--><?php //echo $_info->getAdditionalInformation('lastname'); ?><!--</dt>-->
<!--    <dt class="title">><a target="_blank" href="--><?php //echo $this->getMethod()->getInfoInstance()->getAdditionalInformation('url'); ?><!--">--><?php //echo __("Click here to download Boleto PDF."); ?><!--</a></dt>-->
</dl>
