<?php
$additionalInformation = $this->getInfo()->getAdditionalInformation();
$paymentData = $additionalInformation['transaction_data']['payment'];
?>
<h4>PagoFacil</h4>
<table class="table data-table">
    <tbody>
        <tr>
            <td>Voucher link</td>
            <td>
                <a href="<?php echo $paymentData['voucher_url'] ?>">Click here to print your voucher</a>
            </td>
        </tr>
    </tbody>
</table>
