<?php
$transactionData = $this->getTransactionData();
$dueDate = new \DateTime($transactionData['payment']['due_date']);
?>

<div class="payment-method-details colombia colombia-baloto">
    <h4><?php echo __('Details of your order') ?></h4>
    <p>
        <?php
            echo __(
                sprintf(
                    '%s, your baloto has been generated and the due date is %s.',
                    $this->getOrderCustomerFirstname(),
                    $dueDate->format('d/m/Y')
                )
            )
        ?>
        <br>
        <?php echo __('We send a copy to email') ?> <?php echo $this->getOrderCustomerEmail() ?>.
    </p>

    <div class="voucher-data-box">
        <p class="voucher-id">Voucher ID: <?php echo $transactionData['payment']['voucher_id'] ?></p>
        <a class="voucher-url" href="<?php echo $transactionData['payment']['baloto_url'] ?>" target="_blank"><?php echo __('Print Baloto') ?></a>
    </div>
</div>
