<?php
$transactionData = $this->getTransactionData();
$dueDate = new \DateTime($transactionData['payment']['due_date']);
?>

<div class="payment-method-details brazil-boleto">
    <h4><?php echo __('Details of your order') ?></h4>
    <p>
        <?php
            echo __(
                sprintf(
                    '%s, your boleto bancário has been generated and the due date is %s.',
                    $this->getOrderCustomerFirstname(),
                    $dueDate->format('d/m/Y')
                )
            )
        ?>
        <br>
        <?php echo __('We send a copy to email') ?> <?php echo $this->getOrderCustomerEmail() ?>.
        <br>
        <?php echo __('Pague o boleto no internet banking de seu banco utilizando o código de barras. Você também pode imprimir o boleto e pagar em casas lotéricas ou no caixa de seu banco.') ?>
    </p>

    <div class="boleto-data-box">
        <input class="barcode" value="<?php echo $transactionData['payment']['boleto_barcode'] ?>" readonly/>
        <div class="boleto-actions">
            <a href="#" class="button button-copy"><?php echo __('Copy') ?></a>
            <a href="<?php echo $transactionData['payment']['boleto_url'] ?>&format=pdf" target="_blank" class="button button-pdf"><?php echo __('Save PDF') ?></a>
            <a href="<?php echo $transactionData['payment']['boleto_url'] ?>" target="_blank" class="button button-print"><?php echo __('Print Boleto Bancário') ?></a>
        </div>
        <p class="observation">
            <?php echo __('Dica: pague seu boleto até as 21h de um dia útil e seu pagamento terá a chance de ser confirmado mais rapidamente :)') ?>
        </p>
    </div>
</div>
<script type="text/javascript">
    require(["jquery"], function($) {
        "use strict";
        $('.button-copy').click(function(){
            $('input.barcode').select();
            document.execCommand('copy');
            return false;
        })
    });
</script>
