<?php
$transactionData = $this->getTransactionData();
$dueDate = new \DateTime($transactionData['payment']['due_date']);
?>

<div class="payment-method-details peru peru-pagoefectivo">
    <h4><?php echo __('Details of your order') ?></h4>
    <p>
        <?php
            echo __(
                sprintf(
                    '%s, tu voucher CIP fué generado y la fecha vencimiento %s.',
                    ucwords(strtolower($transactionData['payment']['customer']['name'])),
                    $dueDate->format('d/m/Y')
                )
            )
        ?>
        <br>
        <?php echo __('Enviamos una copia al correo electrónico:') ?> <?php echo $this->getOrderCustomerEmail() ?>.
    </p>

    <div class="voucher-data-box">
        <p class="voucher-id">CIP Code: <?php echo $transactionData['payment']['cip_code'] ?></p>
        <a class="voucher-url" href="<?php echo $transactionData['payment']['cip_url'] ?>" target="_blank"><?php echo __('View CIP') ?></a>
    </div>
</div>
