<div class="ebanx-details">
    <p class="text-center">Baixe o app para IOS ou Android da Conta EBANX.</p>

    <div class="ebanx-groups ebanx-badges">
        <div class="ebanx-group">
            <a href="https://itunes.apple.com/br/app/ebanx/id1062597149?mt=8" target="_blank">
                <img src="<?= $this->getViewFileUrl('Ebanx_Payments::images/badge-apple.png') ?>" alt="Disponível na App Store">
            </a>
        </div>
        <div class="ebanx-group">
            <a href="https://play.google.com/store/apps/details?id=ebanx.ebanx&hl=en" target="_blank">
                <img src="<?= $this->getViewFileUrl('Ebanx_Payments::images/badge-google.png') ?>" alt="Disponível na Google Play">
            </a>
        </div>
    </div>
</div>
