<!-- TODO: CHANGING CSS TO XML -->
<link rel="stylesheet" href="<?= $this->getViewFileUrl('Ebanx_Payments::css/loading.css') ?>" />
<?php
/**
 * @var \Ebanx\Payments\Block\Checkout\Success $this
 */

    $order = $this->getOrder();
    $dueDate = $this->getDueDate();
?>

<div class="ebanx-details">
    
    <div class="defails">
        <p><strong><?= $order->getBillingAddress()->getFirstname(); ?></strong>, seu boleto foi gerado e a data de vencimento é dia
            <strong><?= $dueDate ?></strong> :)</p>
        <p>Enviamos uma cópia para o email <strong><?= $order->getBillingAddress()->getEmail(); ?></strong></p>
        <p>Pague o boleto no Internet Banking de seu banco apenas copiando o código de barras! Você também pode imprimir o
            boleto e pagar em casas lotéricas e no caixa do seu banco.</p>
        <p><b>Dica</b>: Pagar seu boleto até às 21h de dias úteis, faz com que o pagamento tenha a chance de ser confirmado
            mais rápido :)
        </p>
    </div>

    <div>
        <iframe id="ebanx-boleto-frame" src="<?php echo $this->getVoucherUrl(); ?>" style="visibility: hidden; height: 0px;"></iframe>
        <div class="loading-fading-circle">
            <div class="loading-circle1 loading-circle"></div>
            <div class="loading-circle2 loading-circle"></div>
            <div class="loading-circle3 loading-circle"></div>
            <div class="loading-circle4 loading-circle"></div>
            <div class="loading-circle5 loading-circle"></div>
            <div class="loading-circle6 loading-circle"></div>
            <div class="loading-circle7 loading-circle"></div>
            <div class="loading-circle8 loading-circle"></div>
            <div class="loading-circle9 loading-circle"></div>
            <div class="loading-circle10 loading-circle"></div>
            <div class="loading-circle11 loading-circle"></div>
            <div class="loading-circle12 loading-circle"></div>
        </div>
    </div>

    <?php include 'apps.phtml' ?>

    <script src="<?= $this->getViewFileUrl('Ebanx_Payments::js/voucher.js') ?>"></script>

    <style>
        .defails{
            padding: 40px 0 0 0;
        }

        .ebanx-group{
            display: inline-block;
            margin-right: 20px;
        }
    </style>
</div>
