<?php
/**
 * @var \Ebanx\Payments\Block\Success\Redirect $this
 */
$order = $this->getOrder();
?>

<div class="details">
  <p><?= $order->getBillingAddress()->getFirstname(); ?> usted será redirigido a la página de Servipag para completar el pago.</p>
  <p>Si no se redirige en unos instantes <a href="<?= $this->getRedirectUrl() ?>" target="_blank">haga clic aquí</a></p>
  <input id="redirectURL" type="hidden" value="<?= $this->getRedirectUrl() ?>">
</div>
