<?php
/**
 * @var \Ebanx\Payments\Block\Success\Cash $this
 */

$order = $this->getOrder();
$dueDate = $this->getDueDate();
?>

<div class="details">
  <p>¡Listo <strong><?= $order->getBillingAddress()->getFirstname(); ?></strong>!
    Tu boleta EBANX de pago en Spei ha sido generada.</p>
  <p>Enviamos una copia a <strong><?= $order->getBillingAddress()->getEmail(); ?></strong></p>
  <p>No lo olvides: tu boleta vence el día <strong><?= $dueDate ?></strong>.
    Después de esa fecha no será posible realizar el pago y la boleta será cancelada automáticamente.</p>
  <p>¿Dudas? Con gusto te <a href="https://www.ebanx.com/mx/ayuda/pagos/boleta">ayudaremos</a>.</p>
</div>
