<?php
/**
 * @var \Ebanx\Payments\Block\Success\Tef $this
 */
?>

<div class="ebanx-details">

    <div class="details">
        <?= $this->getRedirectUrl() ?>
    </div>


    <?php include 'apps.phtml' ?>

    <style>
        .details{
            padding: 40px 0 0 0;
        }

        .ebanx-group{
            display: inline-block;
            margin-right: 20px;
        }
    </style>
</div>
