<?php
/**
 * @var \Ebanx\Payments\Block\Success\Redirect $this
 */

    $order = $this->getOrder();
?>

<div class="details">
  <p><?= $order->getBillingAddress()->getFirstname(); ?> você será redirecionado para a pagina do seu banco para concluir o pagamento.</p>
  <p>Caso você não seja redirecionado em alguns instantes <a href="<?= $this->getRedirectUrl() ?>" target="_blank">clique aqui</a></p>
  <input id="redirectURL" type="hidden" value="<?= $this->getRedirectUrl() ?>">
</div>
