<?php
$paymentData = $this->getInfo()->getAdditionalInformation();
?>
<h2>Credit Card</h2>
<table class="table data-table">
    <tbody>
        <tr>
            <td>Credit/Debit Card Type</td>
            <td><?php echo $paymentData['payment_type_code'] ?></td>
        </tr>
        <tr>
            <td>Credit Card Masked Number</td>
            <td><?php echo $paymentData['masked_card_number'] ?></td>
        </tr>
        <tr>
            <td>Installments</td>
            <td><?php echo $paymentData['installments'] ?>x</td>
        </tr>
    </tbody>
</table>
