<?php
$transactionData = $this->getTransactionData();
$dueDate = new \DateTime($transactionData['payment']['due_date']);
?>

<div class="payment-method-details argentina argentina-pagofacil">
    <h4><?php echo __('Details of your order') ?></h4>
    <p>
        <?php
            echo __(
                sprintf(
                    '%s, your voucher has been generated and the due date is %s.',
                    $this->getOrderCustomerFirstname(),
                    $dueDate->format('d/m/Y')
                )
            )
        ?>
        <br>
        <?php echo __('We send a copy to email') ?> <?php echo $this->getOrderCustomerEmail() ?>.
    </p>
    <div class="voucher-data-box">
        <a class="voucher-url" href="<?php echo $transactionData['payment']['voucher_url'] ?>" target="_blank">
            <?php echo __('Click here to print your voucher') ?>
        </a>
    </div>
</div>
