<?php
$additionalInformation = $this->getInfo()->getAdditionalInformation();
$paymentData = $additionalInformation['transaction_data']['payment'];
?>
<h2>EBANX - Argentina PagoFacil</h2>
<table class="admin__table-secondary order-information-table">
    <tbody>
        <tr>
            <th>Voucher link</th>
            <td>
                <a href="<?php echo $paymentData['voucher_url'] ?>">Click here to print your voucher</a>
            </td>
        </tr>
    </tbody>
</table>
